// AUTO-GENERATED by scripts/gen-public-config.mjs — do not edit by hand.
//
// Public Supabase config for the production build. The anon key is RLS-protected
// and is downloaded by every browser regardless, so committing it is safe (it is
// NOT the service_role key). This is a FALLBACK: import.meta.env.VITE_* always
// wins when present (local dev + any properly-configured deployment).
export const PUBLIC_SUPABASE_URL = "https://nntkxojdeyziemdhyjvg.supabase.co";
export const PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5udGt4b2pkZXl6aWVtZGh5anZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNTgzNjMsImV4cCI6MjA5NTgzNDM2M30.uVGM-lUw806DyLvQw06vc7Z7Y8C1qUqMvDHqVjlyN3k";
