[project]
ref = "nntkxojdeyziemdhyjvg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
migrations_path = "../scripts/supabase"
seed = false
model = "postgres"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:3000"]

[edge_functions]
enabled = true
include = ["*"]

[storage]
enabled = true

[analytics]
enabled = false
