// SiteTrack Pro - typed database boundary (enterprise hardening P1-C).
//
// `Database` mirrors the LIVE public schema (generated by scripts/generate-db-types.mjs,
// committed as src/lib/database.types.ts). Passing TypedSupabaseClient into a
// query module makes every .from()/.select()/.insert()/.rpc() call compile-time
// checked against real columns — the class of bug where a SELECT names a column
// that does not exist (PGRST204) dies here.
//
// Adoption is incremental: legacy modules keep the untyped client; converted
// modules take TypedSupabaseClient. New modules MUST use it.

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./database.types";

export type { Database, Json } from "./database.types";

export type TypedSupabaseClient = SupabaseClient<Database>;

/** Row / Insert / Update shorthands for a table. */
export type TableRow<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TableInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
export type TableUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"];

/**
 * Same singleton as getClient(), viewed through the schema-generic.
 * The single controlled cast is the migration bridge — runtime behavior and
 * lazy SDK loading are unchanged.
 */
export async function getTypedClient(): Promise<TypedSupabaseClient | null> {
  const { getClient } = await import("./supabase");
  const client = await getClient();
  return client ? (client as unknown as TypedSupabaseClient) : null;
}
