// SiteTrack Pro — finance queries (v3 port, Batch 3). DB-wired to
// purchase_orders / invoices / expenses via the migration 74 bridge.

export type Result<T> = { ok: true; data: T } | { ok: false; error: string };
const ok = <T>(d: T): Result<T> => ({ ok: true, data: d });
const er = (e: unknown): Result<never> => ({ ok: false, error: e instanceof Error ? e.message : String(e) });
const dbe = (e: { message?: string }): Result<never> => ({ ok: false, error: String(e.message ?? e) });
const oneOf = <T extends string>(vals: readonly T[], fb: T) => (v: unknown): T => (vals.includes(v as T) ? (v as T) : fb);

/** Format a rupee amount (stored as a whole-rupee bigint) for display. */
export function fmtRupees(n: number): string {
  return "₹" + (Number.isFinite(n) ? n : 0).toLocaleString("en-IN");
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function upd(client: any, table: string, id: string, patch: Record<string, unknown>): Promise<Result<{ ok: true }>> {
  try { const { error } = await client.from(table).update(patch).eq("id", id); if (error) return dbe(error); return ok({ ok: true }); } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function del(client: any, table: string, id: string): Promise<Result<{ ok: true }>> {
  try { const { error } = await client.from(table).delete().eq("id", id); if (error) return dbe(error); return ok({ ok: true }); } catch (e) { return er(e); }
}

// ── Purchase Orders ───────────────────────────────────────────────────────
export type POStatus = "pending" | "approved" | "delivered" | "cancelled";
export interface PurchaseOrder { id: string; poNo: string; items: string | null; amount: number; status: POStatus; deliveryDate: string | null; }
const asPO = oneOf<POStatus>(["pending", "approved", "delivered", "cancelled"], "pending");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function listPOs(client: any, projectId: string): Promise<Result<PurchaseOrder[]>> {
  try {
    const { data, error } = await client.from("purchase_orders").select("id, po_no, items, amount, status, delivery_date").eq("project_id", projectId).order("created_date", { ascending: false });
    if (error) return dbe(error);
    return ok(((data ?? []) as Array<Record<string, unknown>>).map(r => ({ id: String(r.id), poNo: String(r.po_no ?? ""), items: r.items == null ? null : String(r.items), amount: Number(r.amount ?? 0), status: asPO(r.status), deliveryDate: r.delivery_date == null ? null : String(r.delivery_date) })));
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createPO(client: any, input: { projectId: string; poNo: string; items?: string; amount: number; deliveryDate?: string | null; vendorId?: string | null }): Promise<Result<{ id: string }>> {
  try {
    const { data, error } = await client.from("purchase_orders").insert({ project_id: input.projectId, po_no: input.poNo, items: input.items || null, amount: input.amount, delivery_date: input.deliveryDate || null, vendor_id: input.vendorId || null }).select("id").single();
    if (error) return dbe(error); return ok({ id: String(data.id) });
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const setPOStatus = (client: any, id: string, status: POStatus) => upd(client, "purchase_orders", id, { status });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const deletePO = (client: any, id: string) => del(client, "purchase_orders", id);

// ── Invoices ──────────────────────────────────────────────────────────────
export type InvoiceStatus = "sent" | "paid" | "overdue" | "cancelled";
/** Source of a generated invoice (v4 C2). phase = fee_phases, hourly/retainer = billing engine. */
export type InvoiceSource = "phase" | "hourly" | "retainer";
/** One line of an invoice (v4 C3.3). Generated by the billing RPCs. */
export interface InvoiceLine {
  id: string;
  description: string;
  qty: number;
  unitPrice: number;
  amount: number;
}
export interface Invoice {
  id: string; no: string; amount: number; gst: number; tds: number;
  status: InvoiceStatus; issuedDate: string | null;
  source: InvoiceSource | null; periodFrom: string | null; periodTo: string | null;
  retainerId: string | null; phaseId: string | null;
  lines: InvoiceLine[];
}
const asInv = oneOf<InvoiceStatus>(["sent", "paid", "overdue", "cancelled"], "sent");
const asSource = oneOf<InvoiceSource>(["phase", "hourly", "retainer"], "phase");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function mapLines(raw: unknown): InvoiceLine[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((l) => {
    const r = l as Record<string, unknown>;
    return {
      id: String(r.id ?? ""),
      description: String(r.description ?? ""),
      qty: Number(r.qty ?? 0),
      unitPrice: Number(r.unit_price ?? 0),
      amount: Number(r.amount ?? 0),
    };
  });
}

/** Sum of a line item's amounts (pure — for totals display + tests). */
export function invoiceLinesTotal(lines: InvoiceLine[]): number {
  return (lines ?? []).reduce((s, l) => s + (Number.isFinite(l.amount) ? l.amount : 0), 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function listInvoices(client: any, projectId: string): Promise<Result<Invoice[]>> {
  try {
    const { data, error } = await client.from("invoices").select("id, no, amount, gst, tds, status, issued_date, source, period_from, period_to, retainer_id, phase_id, invoice_lines(id, description, qty, unit_price, amount)").eq("project_id", projectId).order("issued_date", { ascending: false });
    if (error) return dbe(error);
    return ok(((data ?? []) as Array<Record<string, unknown>>).map(r => ({
      id: String(r.id), no: String(r.no ?? ""), amount: Number(r.amount ?? 0), gst: Number(r.gst ?? 0), tds: Number(r.tds ?? 0), status: asInv(r.status), issuedDate: r.issued_date == null ? null : String(r.issued_date),
      source: r.source == null ? null : asSource(r.source),
      periodFrom: r.period_from == null ? null : String(r.period_from),
      periodTo: r.period_to == null ? null : String(r.period_to),
      retainerId: r.retainer_id == null ? null : String(r.retainer_id),
      phaseId: r.phase_id == null ? null : String(r.phase_id),
      lines: mapLines(r.invoice_lines),
    })));
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createInvoice(client: any, input: { projectId: string; no: string; amount: number; gst?: number; tds?: number; phaseId?: string | null }): Promise<Result<{ id: string }>> {
  try {
    const { data, error } = await client.from("invoices").insert({ project_id: input.projectId, no: input.no, amount: input.amount, gst: input.gst ?? 18, tds: input.tds ?? 2, phase_id: input.phaseId ?? null, issued_date: new Date().toISOString().slice(0, 10) }).select("id").single();
    if (error) return dbe(error); return ok({ id: String(data.id) });
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const setInvoiceStatus = (client: any, id: string, status: InvoiceStatus) => upd(client, "invoices", id, { status, paid_date: status === "paid" ? new Date().toISOString().slice(0, 10) : null });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const deleteInvoice = (client: any, id: string) => del(client, "invoices", id);

// ── Expenses (Budget) ─────────────────────────────────────────────────────
export type ExpenseStatus = "recorded" | "reimbursed" | "approved" | "rejected" | "disputed";
export interface Expense { id: string; category: string; description: string; amount: number; paidTo: string | null; expenseDate: string | null; status: ExpenseStatus; }
const asExp = oneOf<ExpenseStatus>(["recorded", "reimbursed", "approved", "rejected", "disputed"], "recorded");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function listExpenses(client: any, projectId: string): Promise<Result<Expense[]>> {
  try {
    const { data, error } = await client.from("expenses").select("id, category, description, amount, paid_to, expense_date, status").eq("project_id", projectId).order("expense_date", { ascending: false });
    if (error) return dbe(error);
    return ok(((data ?? []) as Array<Record<string, unknown>>).map(r => ({ id: String(r.id), category: String(r.category ?? ""), description: String(r.description ?? ""), amount: Number(r.amount ?? 0), paidTo: r.paid_to == null ? null : String(r.paid_to), expenseDate: r.expense_date == null ? null : String(r.expense_date), status: asExp(r.status) })));
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createExpense(client: any, input: { projectId: string; category: string; description: string; amount: number; paidTo?: string; recordedBy: string }): Promise<Result<{ id: string }>> {
  try {
    const { data, error } = await client.from("expenses").insert({ project_id: input.projectId, category: input.category, description: input.description, amount: input.amount, paid_to: input.paidTo || null, recorded_by: input.recordedBy }).select("id").single();
    if (error) return dbe(error); return ok({ id: String(data.id) });
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const setExpenseStatus = (client: any, id: string, status: ExpenseStatus) => upd(client, "expenses", id, { status });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const deleteExpense = (client: any, id: string) => del(client, "expenses", id);

// ── RA Bills (running account) ────────────────────────────────────────────
export type RaBillStatus = "submitted" | "approved" | "paid" | "rejected";
export interface RaBill { id: string; no: string; subcontractor: string | null; scope: string | null; billAmount: number; retentionPct: number; paidAmount: number; status: RaBillStatus; billDate: string | null; }
const asRa = oneOf<RaBillStatus>(["submitted", "approved", "paid", "rejected"], "submitted");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function listRaBills(client: any, projectId: string): Promise<Result<RaBill[]>> {
  try {
    const { data, error } = await client.from("ra_bills").select("id, no, subcontractor, scope, bill_amount, retention_pct, paid_amount, status, bill_date").eq("project_id", projectId).order("bill_date", { ascending: false });
    if (error) return dbe(error);
    return ok(((data ?? []) as Array<Record<string, unknown>>).map(r => ({ id: String(r.id), no: String(r.no ?? ""), subcontractor: r.subcontractor == null ? null : String(r.subcontractor), scope: r.scope == null ? null : String(r.scope), billAmount: Number(r.bill_amount ?? 0), retentionPct: Number(r.retention_pct ?? 0), paidAmount: Number(r.paid_amount ?? 0), status: asRa(r.status), billDate: r.bill_date == null ? null : String(r.bill_date) })));
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createRaBill(client: any, input: { projectId: string; no: string; subcontractor?: string; scope?: string; billAmount: number; retentionPct?: number }): Promise<Result<{ id: string }>> {
  try {
    const { data, error } = await client.from("ra_bills").insert({ project_id: input.projectId, no: input.no, subcontractor: input.subcontractor || null, scope: input.scope || null, bill_amount: input.billAmount, retention_pct: input.retentionPct ?? 5 }).select("id").single();
    if (error) return dbe(error); return ok({ id: String(data.id) });
  } catch (e) { return er(e); }
}
/** Net payable after retention = bill_amount * (1 - retention_pct/100). */
export function raNetPayable(b: { billAmount: number; retentionPct: number }): number { return Math.round(b.billAmount * (1 - (b.retentionPct || 0) / 100)); }
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const setRaBillStatus = (client: any, id: string, status: RaBillStatus, paidAmount?: number) => upd(client, "ra_bills", id, { status, ...(paidAmount != null ? { paid_amount: paidAmount } : {}) });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const deleteRaBill = (client: any, id: string) => del(client, "ra_bills", id);

// ── Ledger (inventory transactions) ───────────────────────────────────────
export type LedgerDirection = "inward" | "outward" | "return" | "wastage";
export interface LedgerTxn { id: string; txnDate: string; material: string; unit: string | null; qty: number; direction: LedgerDirection; source: string | null; refNo: string | null; }
const asDir = oneOf<LedgerDirection>(["inward", "outward", "return", "wastage"], "inward");

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function listLedger(client: any, projectId: string): Promise<Result<LedgerTxn[]>> {
  try {
    const { data, error } = await client.from("inventory_transactions").select("id, txn_date, material, unit, qty, direction, source, ref_no").eq("project_id", projectId).order("txn_date", { ascending: false });
    if (error) return dbe(error);
    return ok(((data ?? []) as Array<Record<string, unknown>>).map(r => ({ id: String(r.id), txnDate: String(r.txn_date ?? ""), material: String(r.material ?? ""), unit: r.unit == null ? null : String(r.unit), qty: Number(r.qty ?? 0), direction: asDir(r.direction), source: r.source == null ? null : String(r.source), refNo: r.ref_no == null ? null : String(r.ref_no) })));
  } catch (e) { return er(e); }
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function createLedgerTxn(client: any, input: { projectId: string; material: string; unit?: string; qty: number; direction: LedgerDirection; source?: string; refNo?: string; recordedBy: string }): Promise<Result<{ id: string }>> {
  try {
    const { data, error } = await client.from("inventory_transactions").insert({ project_id: input.projectId, material: input.material, unit: input.unit || null, qty: input.qty, direction: input.direction, source: input.source || null, ref_no: input.refNo || null, recorded_by: input.recordedBy }).select("id").single();
    if (error) return dbe(error); return ok({ id: String(data.id) });
  } catch (e) { return er(e); }
}
/** Net stock balance per material from a transaction list (inward/return add, outward/wastage subtract). */
export function stockBalance(txns: LedgerTxn[]): Map<string, number> {
  const m = new Map<string, number>();
  for (const t of txns) {
    const sign = t.direction === "inward" || t.direction === "return" ? 1 : -1;
    m.set(t.material, (m.get(t.material) ?? 0) + sign * t.qty);
  }
  return m;
}
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const deleteLedgerTxn = (client: any, id: string) => del(client, "inventory_transactions", id);
