-- SiteTrack Pro — v4 Phase C3.3: invoice line items.
-- Run AFTER 145_deliverable_storage.sql. Idempotent.
--
-- invoice_lines: the per-line breakdown of an invoice (generated by the
-- billing RPCs — hourly = one line per (member, rate); retainer = one line).
-- The invoice.amount stays the authoritative rounded total; line amounts are
-- informational and sum to approximately the invoice total.
--
-- RLS mirrors the invoices gates:
--   read   → member of the invoice's project
--   write  → managers + org admin (incl. project-tier via has_project_role)
--
-- The two billing RPCs (142) are re-created here to also write line items so
-- "mark entries billed" stays atomic with the invoice + lines insert.

BEGIN;

create table if not exists public.invoice_lines (
  id          uuid primary key default gen_random_uuid(),
  invoice_id  uuid not null references public.invoices(id) on delete cascade,
  description text not null,
  qty         numeric(12,2) not null default 1,
  unit_price  numeric(14,2) not null default 0,
  amount      bigint not null default 0,   -- whole ₹
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists idx_invoice_lines_invoice on public.invoice_lines(invoice_id, sort_order);

alter table public.invoice_lines enable row level security;

-- ── RLS: read = project member ───────────────────────────────────────────────
drop policy if exists invoice_lines_read on public.invoice_lines;
create policy invoice_lines_read on public.invoice_lines for select
  using (invoice_id in (
    select i.id from public.invoices i
    where i.project_id in (select user_project_ids())
  ));

-- ── RLS: write = managers + org admin ────────────────────────────────────────
drop policy if exists invoice_lines_write on public.invoice_lines;
create policy invoice_lines_write on public.invoice_lines for all
  using (
    invoice_id in (
      select i.id from public.invoices i
      where i.project_id in (select user_project_ids())
        and (
          is_orgadmin()
          or current_role_text() in ('pm','project_admin','design_head','consultant_head','superadmin')
          or has_project_role(i.project_id, 'pm','project_admin','design_head','consultant_head')
        )
    )
  )
  with check (
    invoice_id in (
      select i.id from public.invoices i
      where i.project_id in (select user_project_ids())
        and (
          is_orgadmin()
          or current_role_text() in ('pm','project_admin','design_head','consultant_head','superadmin')
          or has_project_role(i.project_id, 'pm','project_admin','design_head','consultant_head')
        )
    )
  );

grant select, insert, update, delete on public.invoice_lines to authenticated;

-- ── generate_hourly_invoice (re-created: + line items) ───────────────────────
create or replace function public.generate_hourly_invoice(p_project_id uuid, p_from date, p_to date)
returns uuid
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_total   numeric(14,2);
  v_entries bigint;
  v_invoice uuid;
begin
  if not (is_orgadmin() or current_role_text() in ('pm','project_admin','design_head','consultant_head','superadmin')) then
    raise exception 'only engagement managers may generate invoices' using errcode = '42501';
  end if;
  if not (p_project_id in (select public.user_project_ids())) then
    raise exception 'not a member of this project' using errcode = '42501';
  end if;
  if p_from is null or p_to is null or p_from > p_to then
    raise exception 'invalid billing period' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.invoices
     where project_id = p_project_id and source = 'hourly'
       and period_from = p_from and period_to = p_to
       and status <> 'cancelled'
  ) then
    raise exception 'an invoice already exists for this project and period' using errcode = '23505';
  end if;

  -- Per-entry billing source (entry rate ?? latest rate card <= entry date ?? 0).
  create temp table _hrly on commit drop as
  select te.profile_id,
         p.name as member_name,
         te.hours,
         coalesce(
           te.rate,
           (select rc.rate from public.rate_cards rc
             where rc.project_id = te.project_id
               and rc.profile_id = te.profile_id
               and rc.effective_from <= te.date
             order by rc.effective_from desc
             limit 1),
           0
         ) as rate
    from public.time_entries te
    left join public.profiles p on p.id = te.profile_id
   where te.project_id = p_project_id
     and te.approval_status = 'approved'
     and te.billable
     and not te.billed
     and te.date between p_from and p_to;

  select coalesce(sum(hours * rate), 0), count(*)
    into v_total, v_entries
    from _hrly;

  if v_entries = 0 then
    raise exception 'no approved unbilled hours in period' using errcode = 'P0001';
  end if;
  if v_total <= 0 then
    raise exception 'approved unbilled hours have no rate (set an entry rate or rate card)' using errcode = 'P0001';
  end if;

  insert into public.invoices
    (project_id, no, amount, gst, tds, status, issued_date, source, period_from, period_to)
  values (
    p_project_id,
    'HRY-' || to_char(p_from, 'YYYYMM') || '-' || substr(md5(p_project_id::text || p_from::text || p_to::text), 1, 6),
    round(v_total)::bigint, 18, 2, 'sent', current_date, 'hourly', p_from, p_to
  )
  returning id into v_invoice;

  -- Line items: one per (member, rate).
  insert into public.invoice_lines (invoice_id, description, qty, unit_price, amount, sort_order)
  select v_invoice,
         coalesce(member_name, 'Member'),
         sum(hours),
         rate,
         round(sum(hours) * rate)::bigint,
         row_number() over (order by round(sum(hours) * rate)::bigint desc)
    from _hrly
   group by profile_id, member_name, rate;

  update public.time_entries te
     set billed = true, billed_invoice_id = v_invoice
   where te.project_id = p_project_id
     and te.approval_status = 'approved'
     and te.billable
     and not te.billed
     and te.date between p_from and p_to;

  return v_invoice;
end;
$$;

grant execute on function public.generate_hourly_invoice(uuid, date, date) to authenticated;

-- ── generate_retainer_invoice (re-created: + line item) ──────────────────────
create or replace function public.generate_retainer_invoice(p_retainer_id uuid, p_from date, p_to date)
returns uuid
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_retainer public.retainers%rowtype;
  v_invoice  uuid;
begin
  if not (is_orgadmin() or current_role_text() in ('pm','project_admin','design_head','consultant_head','superadmin')) then
    raise exception 'only engagement managers may generate invoices' using errcode = '42501';
  end if;
  select * into v_retainer from public.retainers where id = p_retainer_id;
  if v_retainer.id is null then
    raise exception 'retainer not found' using errcode = 'P0002';
  end if;
  if v_retainer.status <> 'active' then
    raise exception 'retainer is not active' using errcode = '42501';
  end if;
  if not (v_retainer.project_id in (select public.user_project_ids())) then
    raise exception 'not a member of this project' using errcode = '42501';
  end if;
  if p_from is null or p_to is null or p_from > p_to then
    raise exception 'invalid billing period' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.invoices
     where retainer_id = p_retainer_id and source = 'retainer'
       and period_from = p_from and period_to = p_to
       and status <> 'cancelled'
  ) then
    raise exception 'an invoice already exists for this retainer and period' using errcode = '23505';
  end if;

  insert into public.invoices
    (project_id, no, amount, gst, tds, status, issued_date, source, period_from, period_to, retainer_id)
  values (
    v_retainer.project_id,
    'RTR-' || to_char(p_from, 'YYYYMM') || '-' || substr(md5(p_retainer_id::text || p_from::text || p_to::text), 1, 6),
    v_retainer.monthly_amount, 18, 2, 'sent', current_date, 'retainer', p_from, p_to, p_retainer_id
  )
  returning id into v_invoice;

  insert into public.invoice_lines (invoice_id, description, qty, unit_price, amount, sort_order)
  values (v_invoice, coalesce(v_retainer.title, 'Retainer'), 1, v_retainer.monthly_amount, v_retainer.monthly_amount, 0);

  return v_invoice;
end;
$$;

grant execute on function public.generate_retainer_invoice(uuid, date, date) to authenticated;

DO $$ BEGIN
  RAISE NOTICE '146_invoice_lines: table + RLS + billing RPCs emit line items';
END $$;

COMMIT;
